version: '3.8'

services:

  client:
    stdin_open: true
    command: >
      sh -c "npm i && npm run start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      #- /app/node_modules
      - ./:/app
